AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  RnD

  Sample SAM Template for RnD
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  NodeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: node-function
      CodeUri: functions/node-function/
      Description: "A Node function to process some data."
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        NodeFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /node
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
  PythonFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: python-function
      Description: "A Python function to process some data."
      CodeUri: functions/python-function/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events: 
        PythonFunction:
          Type: Api
          Properties:
            Path: /python
            Method: POST

Outputs:

